services: 
  mongodb: 
    image : mongo
    container_name: mongodbweek14
    ports: 
      - "27017:27017"
    volumes :
      - mongo_data:/data/db

  mongo-express :
    image : mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment : 
      ME_CONFIG_MONGODB_SERVER: mongodbweek14

volumes: 
  mongo_data: 